-- Add lesson lines for all lessons

-- Lesson 2: HTML Elements and Attributes
INSERT INTO lesson_lines (lesson_id, line_number, code_content, line_type) VALUES
(2, 1, '<!DOCTYPE html>', 'html'),
(2, 2, '<html lang="en">', 'html'),
(2, 3, '<head>', 'html'),
(2, 4, '    <meta charset="UTF-8">', 'html'),
(2, 5, '    <title>HTML Elements</title>', 'html'),
(2, 6, '</head>', 'html'),
(2, 7, '<body>', 'html'),
(2, 8, '    <h1 id="main-title" class="heading">Welcome</h1>', 'html'),
(2, 9, '    <p class="intro">This is a paragraph with <strong>bold</strong> and <em>italic</em> text.</p>', 'html'),
(2, 10, '    <a href="https://example.com" target="_blank">Visit Example</a>', 'html'),
(2, 11, '    <img src="image.jpg" alt="Description" width="300" height="200">', 'html'),
(2, 12, '    <div class="container">', 'html'),
(2, 13, '        <span>Inline element</span>', 'html'),
(2, 14, '    </div>', 'html'),
(2, 15, '</body>', 'html'),
(2, 16, '</html>', 'html');

-- Lesson 3: Introduction to CSS
INSERT INTO lesson_lines (lesson_id, line_number, code_content, line_type) VALUES
(3, 1, '<!DOCTYPE html>', 'html'),
(3, 2, '<html lang="en">', 'html'),
(3, 3, '<head>', 'html'),
(3, 4, '    <meta charset="UTF-8">', 'html'),
(3, 5, '    <title>CSS Introduction</title>', 'html'),
(3, 6, '    <style>', 'html'),
(3, 7, '        body {', 'css'),
(3, 8, '            font-family: Arial, sans-serif;', 'css'),
(3, 9, '            background-color: #f0f0f0;', 'css'),
(3, 10, '            margin: 0;', 'css'),
(3, 11, '            padding: 20px;', 'css'),
(3, 12, '        }', 'css'),
(3, 13, '        h1 {', 'css'),
(3, 14, '            color: #333;', 'css'),
(3, 15, '            font-size: 32px;', 'css'),
(3, 16, '            text-align: center;', 'css'),
(3, 17, '        }', 'css'),
(3, 18, '        p {', 'css'),
(3, 19, '            color: #666;', 'css'),
(3, 20, '            line-height: 1.6;', 'css'),
(3, 21, '        }', 'css'),
(3, 22, '    </style>', 'html'),
(3, 23, '</head>', 'html'),
(3, 24, '<body>', 'html'),
(3, 25, '    <h1>Styled Heading</h1>', 'html'),
(3, 26, '    <p>This paragraph has custom styling applied.</p>', 'html'),
(3, 27, '</body>', 'html'),
(3, 28, '</html>', 'html');

-- Lesson 4: CSS Selectors
INSERT INTO lesson_lines (lesson_id, line_number, code_content, line_type) VALUES
(4, 1, '<!DOCTYPE html>', 'html'),
(4, 2, '<html lang="en">', 'html'),
(4, 3, '<head>', 'html'),
(4, 4, '    <meta charset="UTF-8">', 'html'),
(4, 5, '    <title>CSS Selectors</title>', 'html'),
(4, 6, '    <style>', 'html'),
(4, 7, '        /* Element selector */', 'comment'),
(4, 8, '        p {', 'css'),
(4, 9, '            color: blue;', 'css'),
(4, 10, '        }', 'css'),
(4, 11, '        /* Class selector */', 'comment'),
(4, 12, '        .highlight {', 'css'),
(4, 13, '            background-color: yellow;', 'css'),
(4, 14, '        }', 'css'),
(4, 15, '        /* ID selector */', 'comment'),
(4, 16, '        #header {', 'css'),
(4, 17, '            font-size: 24px;', 'css'),
(4, 18, '        }', 'css'),
(4, 19, '        /* Descendant selector */', 'comment'),
(4, 20, '        div p {', 'css'),
(4, 21, '            margin: 10px;', 'css'),
(4, 22, '        }', 'css'),
(4, 23, '        /* Pseudo-class selector */', 'comment'),
(4, 24, '        a:hover {', 'css'),
(4, 25, '            color: red;', 'css'),
(4, 26, '        }', 'css'),
(4, 27, '    </style>', 'html'),
(4, 28, '</head>', 'html'),
(4, 29, '<body>', 'html'),
(4, 30, '    <div id="header">Header</div>', 'html'),
(4, 31, '    <p class="highlight">Highlighted text</p>', 'html'),
(4, 32, '    <div>', 'html'),
(4, 33, '        <p>Nested paragraph</p>', 'html'),
(4, 34, '    </div>', 'html'),
(4, 35, '    <a href="#">Hover me</a>', 'html'),
(4, 36, '</body>', 'html'),
(4, 37, '</html>', 'html');

-- Lesson 5: CSS Layout with Flexbox
INSERT INTO lesson_lines (lesson_id, line_number, code_content, line_type) VALUES
(5, 1, '<!DOCTYPE html>', 'html'),
(5, 2, '<html lang="en">', 'html'),
(5, 3, '<head>', 'html'),
(5, 4, '    <meta charset="UTF-8">', 'html'),
(5, 5, '    <title>Flexbox Layout</title>', 'html'),
(5, 6, '    <style>', 'html'),
(5, 7, '        .container {', 'css'),
(5, 8, '            display: flex;', 'css'),
(5, 9, '            justify-content: space-between;', 'css'),
(5, 10, '            align-items: center;', 'css'),
(5, 11, '            height: 300px;', 'css'),
(5, 12, '            background-color: #e0e0e0;', 'css'),
(5, 13, '        }', 'css'),
(5, 14, '        .item {', 'css'),
(5, 15, '            flex: 1;', 'css'),
(5, 16, '            padding: 20px;', 'css'),
(5, 17, '            margin: 10px;', 'css'),
(5, 18, '            background-color: #4CAF50;', 'css'),
(5, 19, '            color: white;', 'css'),
(5, 20, '            text-align: center;', 'css'),
(5, 21, '        }', 'css'),
(5, 22, '        .item:nth-child(2) {', 'css'),
(5, 23, '            flex: 2;', 'css'),
(5, 24, '        }', 'css'),
(5, 25, '    </style>', 'html'),
(5, 26, '</head>', 'html'),
(5, 27, '<body>', 'html'),
(5, 28, '    <div class="container">', 'html'),
(5, 29, '        <div class="item">Item 1</div>', 'html'),
(5, 30, '        <div class="item">Item 2 (larger)</div>', 'html'),
(5, 31, '        <div class="item">Item 3</div>', 'html'),
(5, 32, '    </div>', 'html'),
(5, 33, '</body>', 'html'),
(5, 34, '</html>', 'html');

